import { type ChangeEvent, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useCreate, useList } from "@refinedev/core";
import { ImagePlus, Loader2 } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { RESOURCES } from "@/constants";
import { uploadToCloudinary } from "@/lib/cloudinary";
import {
  type CreateClassFormInput,
  type CreateClassFormValues,
  createClassSchema,
} from "@/lib/schema";
import type { Subject, User } from "@/types";

export function ClassCreatePage() {
  const navigate = useNavigate();
  const [uploading, setUploading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [bannerPreview, setBannerPreview] = useState<string | null>(null);

  const { result: subjectsResult } = useList<Subject>({
    resource: RESOURCES.subjects,
    pagination: { pageSize: 100 },
  });
  const { result: teachersResult } = useList<User>({
    resource: RESOURCES.users,
    pagination: { pageSize: 100 },
    filters: [{ field: "role", operator: "eq", value: "teacher" }],
  });

  const { mutate: createClass } = useCreate();

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors },
  } = useForm<CreateClassFormInput, unknown, CreateClassFormValues>({
    resolver: zodResolver(createClassSchema),
    defaultValues: { capacity: 30 },
  });

  const bannerPubId = watch("banner_cld_pub_id");

  async function handleBannerChange(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;

    setUploading(true);
    try {
      const { secure_url, public_id } = await uploadToCloudinary(file);
      setValue("banner_url", secure_url, { shouldValidate: true });
      setValue("banner_cld_pub_id", public_id, { shouldValidate: true });
      setBannerPreview(secure_url);
    } catch (error) {
      console.error(error);
    } finally {
      setUploading(false);
    }
  }

  function onSubmit(values: CreateClassFormValues) {
    setIsSaving(true);
    createClass(
      { resource: RESOURCES.classes, values },
      {
        onSuccess: () => navigate("/classes"),
        onError: () => setIsSaving(false),
      },
    );
  }

  return (
    <div className="mx-auto max-w-2xl">
      <Card>
        <CardHeader>
          <CardTitle>Create a class</CardTitle>
          <CardDescription>
            Sections require a subject, a teacher, and a capacity. The invite
            code is generated by the backend.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form className="space-y-5" onSubmit={handleSubmit(onSubmit)}>
            <div className="space-y-1.5">
              <Label htmlFor="name">Class name</Label>
              <Input
                id="name"
                placeholder="Python Foundations - Section A"
                {...register("name")}
              />
              {errors.name && (
                <p className="text-xs text-destructive">
                  {errors.name.message}
                </p>
              )}
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="description">Description</Label>
              <Textarea id="description" {...register("description")} />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <Label htmlFor="subject_id">Subject</Label>
                <Select id="subject_id" {...register("subject_id")}>
                  <option value="">Select a subject</option>
                  {subjectsResult?.data.map((subject) => (
                    <option key={subject.id} value={subject.id}>
                      {subject.code} — {subject.name}
                    </option>
                  ))}
                </Select>
                {errors.subject_id && (
                  <p className="text-xs text-destructive">
                    {errors.subject_id.message}
                  </p>
                )}
              </div>

              <div className="space-y-1.5">
                <Label htmlFor="teacher_id">Teacher</Label>
                <Select id="teacher_id" {...register("teacher_id")}>
                  <option value="">Select a teacher</option>
                  {teachersResult?.data.map((teacher) => (
                    <option key={teacher.id} value={teacher.id}>
                      {teacher.name}
                    </option>
                  ))}
                </Select>
                {errors.teacher_id && (
                  <p className="text-xs text-destructive">
                    {errors.teacher_id.message}
                  </p>
                )}
              </div>
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="capacity">Capacity</Label>
              <Input
                id="capacity"
                type="number"
                min={1}
                {...register("capacity")}
              />
              {errors.capacity && (
                <p className="text-xs text-destructive">
                  {errors.capacity.message}
                </p>
              )}
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="banner">Banner image</Label>
              <div className="flex items-center gap-3">
                <label
                  htmlFor="banner"
                  className="flex h-24 w-40 shrink-0 cursor-pointer items-center justify-center rounded-md border border-dashed text-muted-foreground hover:bg-accent"
                >
                  {uploading ? (
                    <Loader2 className="size-5 animate-spin" />
                  ) : bannerPreview ? (
                    <img
                      src={bannerPreview}
                      alt="Banner preview"
                      className="h-full w-full rounded-md object-cover"
                    />
                  ) : (
                    <ImagePlus className="size-5" />
                  )}
                </label>
                <input
                  id="banner"
                  type="file"
                  accept="image/*"
                  className="hidden"
                  onChange={handleBannerChange}
                />
                <p className="text-xs text-muted-foreground">
                  Uploaded directly to Cloudinary. {bannerPubId ? "Uploaded ✓" : "Optional."}
                </p>
              </div>
            </div>

            <Button type="submit" disabled={isSaving || uploading}>
              {isSaving ? "Creating..." : "Create class"}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
